services:
  - type: web
    runtime: node
    name: noce-florale
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    plan: standard
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        value: /graphql
      - key: CORS_ORIGIN
        value: https://noce-florale.onrender.com
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        sync: false # Prevents this from being synced on service update
      - key: JWT_REFRESH_SECRET
        sync: false # Prevents this from being synced on service update
      - key: CLOUDINARY_CLOUD_NAME
        value: dros6cd9l
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 5
